# Generated by Django 2.2.3 on 2019-10-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerName', models.CharField(max_length=100)),
                ('Rent', models.IntegerField()),
                ('Area', models.IntegerField(default=None)),
                ('NoOfBedrooms', models.IntegerField(default=None)),
                ('Parking', models.BooleanField(default=False)),
                ('img', models.FileField(default='images/default-img.png', upload_to='images/')),
                ('img2', models.ImageField(default='images/default-img.png', upload_to='images/')),
                ('img3', models.ImageField(default='images/default-img.png', upload_to='images/')),
                ('NoOfBathrooms', models.IntegerField(default=None, null=True)),
                ('Description', models.TextField(default='Good location near by Santa Garden')),
                ('Address', models.TextField(default='B14, Varlin Park, Poll Street, Bangluru - 114567')),
                ('ListedByOwner', models.BooleanField(default=True)),
                ('ListedByBroker', models.BooleanField(default=False)),
                ('Type', models.CharField(default='Appartment', max_length=15)),
                ('MobileNumber', models.IntegerField()),
                ('Email', models.TextField(default=None, max_length=50)),
            ],
        ),
    ]
